config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get    'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch  'tasks/:id',      to: 'tasks#update'
  delete 'tasks/:id',      to: 'tasks#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,700&display=swap">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Poppins:400,500,700&display=swap">
    <style>

      body {
        background: #DEDEDE;
      }

      h1 {
        line-height: 2;
        background-color: #BEEEF7;
        text-align: center;
        font-family: 'Poppins', serif;
        font-size: 23px;
        text-shadow: 4px 4px 4px #aaa;
      }

      a, label, h2, h3 {
        color: black;
        font-family: 'Poppins', serif;
        font-size: 16px;
        font-weight: lighter;
        padding-left: 8px;

      }

      h4 {
        color: #182952;
        font-family: 'Poppins', serif;
        font-size: 14px;
        font-weight: lighter;
        padding-left: 8px;

      }

      ul {
        font-family: 'Nunito Sans', sans-serif;
        font-size: 18px;
        font-weight: lighter;
        list-style: none;
      }

      #add {
        font-family: 'Poppins', serif;
        font-size: 18px;
        text-shadow: 4px 4px 4px #aaa;
      }

    </style>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<h1> Add New Task</h1>
<form action="/tasks" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <label for="title">Title: </label>
  <input type="text" name="task[title]" id="title">

  <label for="details">Details: </label>
  <input type="text" name="task[details]" id="details">

  <input type="submit" value="Create Task">
</form>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks:</h1>
<ul>
  <% @tasks.each do |task| %>
  <li>
    <% if task.completed %>
      <i class="far fa-check-square"></i>
    <% else %>
      <i class="far fa-square"></i>
    <% end %>
    <%= link_to(task.title, task_path(task)) =%>

    <%= link_to destroy_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } do %>
      <i class="far fa-trash-alt fa-sm" style="color:#00334E"></i>
      <% end %>
  </li>
  <% end %>
</ul>
<div id='add'>
<%= link_to "Add New Task", new_task_path %>
</div>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>
<div id='add'>
<%= link_to "Back to All Tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<h1>Task/Status:</h1>
<h2> Title: <%= @task.title%></h2>
<h3>Details: <%= @task.details %></h3>
<h4>
<% if @task.completed %>
      <i class="far fa-check-square"></i> This task is completed
    <% else %>
      <i class="far fa-square"></i> Completed
    <% end %>
</h4>
<div id='add'>
<%= link_to("Back to list", tasks_path) %> or <%= link_to("Edit", edit_task_path(@task)) %>
</div>